spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/ecommerceDB"
    username: postgres
    password: Simform@123
  kafka:
    request:
      topic: user_topic
      topic2: user_save
      topic3: cart_item
    reply:
      topic: result
    group:
        id: user-result-group
        id2: user-save-group
        id3: cart-fetch
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      enable-auto-commit: false
#      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: '*'
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: demodevnick5000@gmail.com
#    password: foucrmdfqfoqpqet
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

server:
  port: 8081


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka/


